// 콘텐츠 생성기 공통 도구 — HTML 이스케이프, 안전한 링크, 날짜, 슬러그.
// 모든 데이터 유래 문자열은 esc() 를 거쳐 HTML 에 들어간다.

export const SITE_URL = 'https://sobangcheck.com';
export const SITE_NAME = '소방체크';

// 생성 파일 표시 — 빌드는 이 표시가 있는 파일만 덮어쓰거나 지운다(손으로 쓴 페이지 보호)
export const GENERATED_MARKER = '<!-- generated by scripts/content/build.mjs';

export class BuildError extends Error {
  constructor(message) {
    super(message);
    this.name = 'BuildError';
  }
}

const HTML_ESCAPES = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' };

/** 텍스트·속성값 공용 이스케이프 (속성은 항상 큰따옴표로 감싼다) */
export function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, (c) => HTML_ESCAPES[c]);
}

/**
 * 링크 주소 검사. 허용: https?:// 절대 주소, 사이트 루트 기준 경로(/...), 같은 페이지 앵커(#...).
 * 그 밖의 스킴(javascript:, data: 등)·프로토콜 상대 주소(//, /\)·공백·제어문자·역슬래시는 거부(null).
 */
export function safeHref(raw) {
  if (typeof raw !== 'string') return null;
  const url = raw.trim();
  if (!url || /[\u0000- \u007f-\u009f\\]/.test(url)) return null;
  if (url.startsWith('#')) return url;
  if (url.startsWith('/')) return url.startsWith('//') ? null : url;
  if (!/^https?:\/\//i.test(url)) return null;
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') return null;
    if (!parsed.hostname) return null;
  } catch {
    return null;
  }
  return url;
}

/** 사이트 밖으로 나가는 링크인지 (새 창 + rel="noopener" 대상) */
export function isExternal(href) {
  if (!/^https?:\/\//i.test(href)) return false;
  try {
    const host = new URL(href).hostname.toLowerCase();
    return host !== 'sobangcheck.com' && host !== 'www.sobangcheck.com';
  } catch {
    return true;
  }
}

/** <a> 태그 — 주소가 안전하지 않으면 링크 없이 글자만 */
export function link(href, text, { className } = {}) {
  const safe = safeHref(href);
  if (!safe) return esc(text);
  const cls = className ? ` class="${esc(className)}"` : '';
  const ext = isExternal(safe) ? ' target="_blank" rel="noopener"' : '';
  return `<a href="${esc(safe)}"${cls}${ext}>${esc(text)}</a>`;
}

/** JSON-LD <script> — 문자열 안의 < > & 와 줄 구분자를 \\u 로 바꿔 script 탈출을 막는다 */
export function jsonLdScript(obj) {
  const json = JSON.stringify(obj, null, 2)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
  return `<script type="application/ld+json">\n${json}\n</script>`;
}

// ── 날짜 ─────────────────────────────────────────────────────────────
// 데이터는 YYYYMMDD(ymd), 프론트매터·사이트맵은 YYYY-MM-DD(iso). 시계는 쓰지 않는다(결정적 출력).

export function isValidYmd(ymd) {
  if (typeof ymd !== 'string' || !/^\d{8}$/.test(ymd)) return false;
  const y = Number(ymd.slice(0, 4));
  const m = Number(ymd.slice(4, 6));
  const d = Number(ymd.slice(6, 8));
  const t = new Date(Date.UTC(y, m - 1, d));
  return t.getUTCFullYear() === y && t.getUTCMonth() === m - 1 && t.getUTCDate() === d;
}

export function isValidIsoDate(iso) {
  return typeof iso === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(iso) && isValidYmd(iso.replace(/-/g, ''));
}

export const isoToYmd = (iso) => iso.replace(/-/g, '');
export const ymdToIso = (ymd) => `${ymd.slice(0, 4)}-${ymd.slice(4, 6)}-${ymd.slice(6, 8)}`;

/** 20241231 → 2024.12.31 (조회 화면과 같은 표기) */
export const fmtDot = (ymd) => `${ymd.slice(0, 4)}.${ymd.slice(4, 6)}.${ymd.slice(6, 8)}`;

/** 2024-12-31 → 2024년 12월 31일 */
export function fmtKo(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  return `${y}년 ${m}월 ${d}일`;
}

export function addDays(ymd, n) {
  const t = new Date(Date.UTC(Number(ymd.slice(0, 4)), Number(ymd.slice(4, 6)) - 1, Number(ymd.slice(6, 8)) + n));
  return `${t.getUTCFullYear()}${String(t.getUTCMonth() + 1).padStart(2, '0')}${String(t.getUTCDate()).padStart(2, '0')}`;
}

const DOW = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MON = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

/** RSS pubDate (RFC 822) — 날짜만 있으므로 한국 시간 자정으로 둔다 */
export function rfc822(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  const dow = new Date(Date.UTC(y, m - 1, d)).getUTCDay();
  return `${DOW[dow]}, ${String(d).padStart(2, '0')} ${MON[m - 1]} ${y} 00:00:00 +0900`;
}

export const maxIso = (...dates) => dates.filter(Boolean).sort().at(-1) ?? null;

// ── 슬러그 ───────────────────────────────────────────────────────────

/** data/02_neighborhood_facilities.json → neighborhood-facilities */
export function useSlugFromFile(fileName) {
  return fileName.replace(/\.json$/, '').replace(/^\d{2}_/, '').replace(/_/g, '-');
}

/** facilities.json 의 id(auto_fire_detection) → auto-fire-detection */
export const facilitySlug = (id) => id.replace(/_/g, '-');

export const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** 조사 선택: 받침 있으면 first(은/이/을), 없으면 second(는/가/를). 한글이 아니면 괄호 병기 */
export function josa(word, first, second) {
  const ch = String(word).trim().slice(-1);
  const code = ch.charCodeAt(0);
  if (code < 0xac00 || code > 0xd7a3) return `${word}${first}(${second})`;
  return `${word}${(code - 0xac00) % 28 ? first : second}`;
}
